### ISSUE TITLE
Suricata not alerting on file download via HTTP

### ISSUE THREAD

**Issue by ngms17** [3CORESec/testmynids.org#2]
I am using the ET Open ruleset but when i test the 6) or 7) Suricata does not give me an alert. But i can see the traffic on the events log. What am i doing wrong?

Also not alerting on 1) and 2) aswell

**Comment by 0xtf** [comment]
Hi @ngms17 

Somehow I missed this. I'm not sure we'll be able to help you with troubleshooting Suricata detections, unfortunately. From a quick test, those tests are still firing as they are supposed to. Namely they will fire (T6 and T7):

- 2013414
- 2014819
- 2018959
- 2011507

If you're not getting alerts I recommend you go over your Suricata configuration.
